### ISSUE TITLE
nearley-test fails on piped input

### ISSUE THREAD

**Issue by rahatarmanahmed** [Hardmath123/nearley#108]
To reproduce, create this grammar:

```sh
echo 'thing -> "wow"' > g.ne
nearleyc g.ne -o g.js
```

I verified the grammar with the unparser:

```sh
nearley-unparse -s thing g.js
wow
```

Passing the input into nearley-test via `-i` works:

```sh
nearley-test -i "wow" g.js
Table length: 4
Number of parses: 1
Parse Charts
Chart: 0
0: {thing →  ● thing$string$1}, from: 0
1: {thing$string$1 →  ● "w" "o" "w"}, from: 0

Chart: 1
0: {thing$string$1 → "w" ● "o" "w"}, from: 0

Chart: 2
0: {thing$string$1 → "w" "o" ● "w"}, from: 0

Chart: 3
0: {thing$string$1 → "w" "o" "w" ● }, from: 0
1: {thing → thing$string$1 ● }, from: 0


Parse results:
[ [ 'wow' ] ]
```

But piping it via stdin doesn't:

```sh
echo "wow" | nearley-test g.js
/Users/rahat/.nvm/versions/node/v6.0.0/lib/node_modules/nearley/lib/nearley.js:237
            throw err;
            ^

Error: nearley: No possible parsings (@3: '
').
    at Parser.feed (/Users/rahat/.nvm/versions/node/v6.0.0/lib/node_modules/nearley/lib/nearley.js:232:23)
    at StreamWrapper.write [as _write] (/Users/rahat/.nvm/versions/node/v6.0.0/lib/node_modules/nearley/lib/stream.js:12:18)
    at doWrite (_stream_writable.js:306:12)
    at writeOrBuffer (_stream_writable.js:292:5)
    at StreamWrapper.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
```

Same thing happens if you try to pipe the unparser into the tester, which I'd expect would necessarily always produce valid results:

```sh
nearley-unparse -s thing g.js | nearley-test g.js
```

I'm using Node 6.0.0 and nearley 2.6.0

**Update:** Whoops, this is because echo and nearley-unparse have a `\n` at the end of the input, which isn't handled by the grammar. So not an issue with nearley-test. Hopefully this helps someone else with the same issue.

**Comment by Hardmath123** [comment]
Yeah, newline characters are gotchas. Glad you figured it out! :-)
