### ISSUE TITLE
Why won't this compile?

### ISSUE THREAD

**Issue by scratchyone** [Hardmath123/nearley#116]
I wrote this grammar:
```
@builtin "whitespace.ne" # `_` means arbitrary amount of whitespace
@builtin "number.ne"     # `int`, `decimal`, and `percentage` number primitives

commands -> print
print -> "print(" ws sn ws ")" sc
ws -> _|""
sn -> [0-9a-zA-Z]
sc -> [](\;)?]
```
for some reason, when I try to compile it, nearley says
```
Error: nearley: No possible parsings (@183: '(').
    at Parser.feed (/usr/local/lib/node_modules/nearley/lib/nearley.js:268:23)
    at StreamWrapper.write [as _write] (/usr/local/lib/node_modules/nearley/lib/stream.js:12:18)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at StreamWrapper.Writable.write (_stream_writable.js:207:11)
    at ReadStream.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
```
Why is this happening?
Thanks!

**Comment by Hardmath123** [comment]
`sc -> [](\;)?]` makes no sense.

**Comment by scratchyone** [comment]
Oh! Thanks! That was supposed to be "[;?]". But it still doesn't compile. Why is that? That is supposed to be a regex

**Comment by scratchyone** [comment]
Nvm, got it!
