### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by swooboo** [Hardmath123/nearley#141]
Hi. Trying to install:

```
sergey@black:~$ sudo npm install -g nearley
npm http GET http://registry.npmjs.org/nearley
npm http 304 http://registry.npmjs.org/nearley
npm http GET http://registry.npmjs.org/cli-color
npm http GET http://registry.npmjs.org/nomnom
npm http GET http://registry.npmjs.org/railroad-diagrams
npm http GET http://registry.npmjs.org/randexp
npm http 304 http://registry.npmjs.org/railroad-diagrams
npm ERR! error installing nearley@2.7.8

npm ERR! Error: No compatible version found: railroad-diagrams@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at /usr/share/npm/lib/cache.js:375:15
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/sergey/nearley/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.2.0-102-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "nearley"
npm ERR! cwd /home/sergey/nearley
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: railroad-diagrams@'^1.0.0'
npm ERR! message Valid install targets:
npm ERR! message ["1.0.0"]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sergey/nearley/npm-debug.log
npm not ok
sergey@black:~$
```

When installing `railroad-diagrams`, some other package is missing, but when I install that, the railroad is missing again.

Any help please? Also I `git clone`'d the repo, but don't know how to run it without `npm`

**Comment by Hardmath123** [comment]
Your node and npm versions are like *years* old. Try updating to newer versions and trying again.

**Comment by swooboo** [comment]
How? I just did `sudo apt-get install npm`. I have Ubuntu 12.04 LTS.

**Comment by swooboo** [comment]
Never mind, needed to add a repository:

```
 1389  sudo apt-get purge nodejs npm
 1390  sudo add-apt-repository ppa:chris-lea/node.js
 1391  sudo apt-get update
 1392  sudo apt-get install nodejs
 1393  npm -v
 1394  sudo npm install -g nearley
```

All good now.
