### ISSUE TITLE
No possible parsings (@0: '/') when using nearley-railroad

### ISSUE THREAD

**Issue by TMiguelT** [Hardmath123/nearley#147]
I compiled my grammar, which worked fine, then tried to use the railroad generator, but that failed with the error below. Any insights?
```
$ nearleyc src/core/grammar.ne > grammar_test.js 
$ nearley-railroad grammar_test.js -o grammar.html
/usr/lib/node_modules/nearley/lib/nearley.js:275
            throw err;
            ^

Error: nearley: No possible parsings (@0: '/').
    at Parser.feed (/usr/lib/node_modules/nearley/lib/nearley.js:270:23)
    at StreamWrapper.write [as _write] (/usr/lib/node_modules/nearley/lib/stream.js:12:18)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at StreamWrapper.Writable.write (_stream_writable.js:247:11)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
```

**Comment by Hardmath123** [comment]
nearley-railroad doesn't take a js file as input, it takes an ne file directly. This is because compilation hides some of the higher-level features of the grammar (such as EBNF, which gets compiled to BNF but ideally should be shown in the railroad diagram anyway).

**Comment by TMiguelT** [comment]
Oh of course! Thank you!
