### ISSUE TITLE
nearleyc forgot a "}"

### ISSUE THREAD

**Issue by linkpy** [Hardmath123/nearley#190]
Hello. I use nearley for parsing a simple LISP-like syntax, but each time I compile the *.ne file, I need to add a "}" at a specific place in the generated *.js file.

Here is my *.ne file (preprocessor code removed for clarity) : 

~~~~~~ne
MAIN -> [\s\n]:* DEFINES [\s\n]:*


DEFINES ->
	  DEFINE SP DEFINES
	| DEFINE

DEFINE -> "(define" SP KL_REF SP EXPRS ")"


EXPRS ->
	  EXPR SP EXPRS
	| EXPR

EXPR ->
	  "(" NAME SP ARGS ")"
	| "(" OP SP ARGS ")"
	| "(" NAME ")" 


ARGS ->
	  ARG SP ARGS
	| ARG

ARG -> KL_REF | STRING | NUMBER | EXPR


OP ->
	  "+" | "-" | "*" | "/" | "&"  | "|" 
	| "=" | "~" | ">" | "<" | ">=" | "<="

NAME -> [a-z] [a-z\-]:*
STRING -> "\"" .:* "\"" 
NUMBER ->
	  [0-9]:+ "." [0-9]:+
	| [0-9]:+

KL_REF -> "@" NAME

NL -> "\n":+									
SP -> [\s\n]:+
~~~~~~

The "}" is forgotten for the NL rule :

~~~~~~js
    // ...
    {"name": "NUMBER$ebnf$3", "symbols": [/[0-9]/]},
    {"name": "NUMBER$ebnf$3", "symbols": ["NUMBER$ebnf$3", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "NUMBER", "symbols": ["NUMBER$ebnf$3"], "postprocess": function(d) { return klast.number( parseInt( d[ 0 ].join( "" ) ) ); }},
    {"name": "KL_REF", "symbols": [{"literal":"@"}, "NAME"], "postprocess": function(d) { return klast.knowledge_ref( d[1] );}, // <<<== A } is missing here
    {"name": "NL$ebnf$1", "symbols": [{"literal":"\n"}]},
    {"name": "NL$ebnf$1", "symbols": ["NL$ebnf$1", {"literal":"\n"}], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    // ...
~~~~~~

If I don't add manually the "}", when I test the parser, I have the following error :

~~~~~~
/.../knowledge-lang-grammar.js:56
    {"name": "NL$ebnf$1", "symbols": [{"literal":"\n"}]},
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at new require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nearley/bin/nearley-test.js:49:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
~~~~~~

Maybe I done something wrong, but the parser works flawlessly with the additional "}".

**Comment by tjvr** [comment]
I can't reproduce this. Using current master 656149f, I get this: https://gist.github.com/tjvr/4ff15dbda50348df107a488e4313d20d

What version of nearley are you using?

**Comment by linkpy** [comment]
I just use NPM version : 2.7.14.

**Comment by tjvr** [comment]
What version of nearley are you using?

**Comment by Hardmath123** [comment]
Can you show it to us with the preprocessor code included? Especially the one for `KL_REF -> "@" NAME`.

**Comment by linkpy** [comment]
Problem solved. I thought it was a bug but it was me who forgotten the final "}" of the preprocessor code's function. Sorry for the trouble.
