### ISSUE TITLE
@preprocessor typescript doesn't work with EBNF (:+, :*, etc)

### ISSUE THREAD

**Issue by SmaugTheGreat** [Hardmath123/nearley#223]
When using a .ne-file like this:

```
@preprocessor typescript

test -> [a-z]:+
```

then this error occurs:

```
[...]\node_modules\nearley\lib\generate.js:18
    var lines = func.toString().split(/\n/);
                    ^

TypeError: Cannot read property 'toString' of undefined
    at dedentFunc ([...]\node_modules\nearley\lib\generate.js:18:21)
    at serializeRule ([...]\node_modules\nearley\lib\generate.js:92:53)
    at [...]\node_modules\nearley\lib\generate.js:13:14
    at Array.map (native)
    at serializeRules ([...]\node_modules\nearley\lib\generate.js:12:30)
    at Function.generate.ts.generate.typescript ([...]\node_modules\nearley\lib\generate.js:178:37)
    at generate ([...]\node_modules\nearley\lib\generate.js:107:48)
    at StreamWrapper.<anonymous> ([...]\node_modules\nearley\bin\nearleyc.js:52:22)
    at emitNone (events.js:91:20)
    at StreamWrapper.emit (events.js:185:7)
```

Tested on Node.js 6.4.0 and 7.9.0 with NPM 4.0.5 and 4.5.0 on Windows 7 x64

**Comment by tjvr** [comment]
Which version of nearley are you using?

**Comment by SmaugTheGreat** [comment]
2.8.0, installed it yesterday.

**Comment by Hardmath123** [comment]
I think the issue is that the whole "builtinPostprocessors" thing is broken, which causes problems near line 88. Can we perhaps refactor that to not special-case these "built-in" postprocessors?

**Comment by tjvr** [comment]
> Can we perhaps refactor that to not special-case these "built-in" postprocessors?

Absolutely—we should replace this with some fixed source code included at the top of every generated file.

@SmaugTheGreat Are you interested in sending a pull request for this? That would be great :D

**Comment by Hardmath123** [comment]
To be honest, I didn't even *know* that some of these builtins were built in. I don't think they're documented nicely anywhere, because nobody uses them afaik. :-/
