### ISSUE TITLE
@include in multiple files

### ISSUE THREAD

**Issue by kasbah** [Hardmath123/nearley#230]
At the moment you can't seem to be able to include a file in multiple files that are themselves also included.

grammar.ne
```
@include "a.ne"
@include "c.ne"

main -> a | c
```

a.ne
```
@include "b.ne"

a -> "a" | b
```

b.ne
```
b -> "b"
```

c.ne
```
@include "b.ne"

c -> "c" | b
```

Results in a warning: 
```
WARN	Undefined symbol `b` used.
```

If c.ne is excluded then there is no warning. It severely limits you in using several files and re-using logic.

**Comment by somebody1234** [comment]
No, it works perfectly fine, the issue is with the linter.

**Comment by kasbah** [comment]
Another related issue is that nearleyc get's confused about the directory:
```
.
├── dir
│   ├── a.ne
│   └── b.ne
└── grammar.ne
```

grammar.ne
```
@include "dir/a.ne"

main -> a
```
a.ne
```
@include "b.ne"

a -> "a" | b
```
b.ne
```
b -> "b"
```


```
$ nearleyc grammar.ne -o grammar.js
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmp/eg/b.ne'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Compile (/tmp/eg/node_modules/nearley/lib/compile.js:49:39)
    at Compile (/tmp/eg/node_modules/nearley/lib/compile.js:53:25)
    at StreamWrapper.<anonymous> (/tmp/eg/node_modules/nearley/bin/nearleyc.js:57:17)
    at emitNone (events.js:91:20)
    at StreamWrapper.emit (events.js:185:7)
    at finishMaybe (_stream_writable.js:512:14)
    at endWritable (_stream_writable.js:522:3)
```
