### ISSUE TITLE
Moo tokenizers work fine for nearley-test but not for real code

### ISSUE THREAD

**Issue by AlexYegupov** [Hardmath123/nearley#331]
Something wrong - simplest example with tokenizers (from https://nearley.js.org/docs/tokenizers) isn't working but nearley-test for same grammar works fine. Want to understand what I do wrong.

Repository with code - https://github.com/AlexYegupov/test-nearley
```
% npm run start                                                      
> @ start /tmp/test-nearley
> ./build-and-test2.sh
/tmp/test-nearley/node_modules/nearley/lib/nearley.js:323
            throw err;
            ^
Error: invalid syntax at line 1 col 1:
  3 * 2
  ^
Unexpected "3"
    at Parser.feed (/tmp/test-nearley/node_modules/nearley/lib/nearley.js:320:23)
    at Object.<anonymous> (/tmp/test-nearley/calculator2.js:8:68)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `./build-and-test2.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/av/.npm/_logs/2017-12-15T13_52_48_424Z-debug.log


% npm run test                                                         # 1 master v8.9.1 15:52
> @ test /tmp/test-nearley
> $(npm bin)/nearley-test -i '2 * 3' ./grammar2.js

Table length: 6
Number of parses: 1
Parse Charts
Chart: 0
0: {multiplication →  ● %number %ws %times %ws %number}, from: 0

Chart: 1
0: {multiplication → %number ● %ws %times %ws %number}, from: 0

Chart: 2
0: {multiplication → %number %ws ● %times %ws %number}, from: 0

Chart: 3
0: {multiplication → %number %ws %times ● %ws %number}, from: 0

Chart: 4
0: {multiplication → %number %ws %times %ws ● %number}, from: 0

Chart: 5
0: {multiplication → %number %ws %times %ws %number ● }, from: 0


Parse results:
[ 6 ]




% node -v                                                             
v8.9.1

% npm -v                                                               
5.6.0

% lsb_release -a                                                      
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

% nearleyc -v                                                          
2.11.0
```
Repository with code above: https://github.com/AlexYegupov/test-nearley

Thanks.

**Comment by tjvr** [comment]
Aha! The problem is the line `new nearley.Parser`. You need to use `Grammar.fromCompiled` here—see the docs :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlexYegupov** [comment]
Thank you!!! Seems works fine now. 

PS Maybe it worth to add at least one example or test with moo to code

**Comment by freddi301** [comment]
```javascript
new nearley.Parser(nearley.Grammar.fromCompiled(grammar))
```
